spring:
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    url: jdbc:mysql://localhost:3306/${db_name}?useSSL=false
    username: root
    password: petclinic
    initialization-mode: ALWAYS